### ISSUE TITLE
'ascii' codec can't encode

### ISSUE THREAD

**Issue by pedrotk** [kunesj/omad#10]
Manga tested for that error
- Ai Yori Aoshi from MangaFox ( [link] [link-1] )
    - Chapter 30 ( Ai Yori Aoshi 30 Kichou—Return )
- Yotsubato! from MangaFox ( [link] [link-2] )
    - Chapter 2 ( Try! Try! Try! Episode minus 1, Ena-chanÂ´s mishap )

Python version:  Python 2.7.9  && Python 3.4.2

**Erro Log 1 (First manga)**:
>!!! Exception: 'ascii' codec can't encode character u'\u2014' in position 22: ordinal not in range(128)
>Download Finished!!!

**Erro Log 2 (Second manga)**:
>!!! Exception: 'ascii' codec can't encode characters in position 52-53: ordinal not in range(128)
>Download Finished!!!

[link-1]:http://mangafox.me/manga/ai_yori_aoshi/ 
[link-2]:http://mangafox.me/manga/yotsubato/

**Comment by pedrotk** [comment]
I update the OMAD from v0.2 to v1.0-pre, still same issue, bug get stuck when try to compress the chapter and don't show any message from error.

**Comment by kunesj** [comment]
Thanks, it should be fixed now. Can you test it directly directly from git, or do I need to build it for you?

**Comment by pedrotk** [comment]
I can't build now, in some hours i come back to build here.

**Comment by pedrotk** [comment]
Build here, tested, work fine now

> Downloading 27/27
>Compressing to: Ai_Yori_Aoshi_30Kichou—Return.zip
>Downloading progress: 2/125

Thanks.
